[package]
name = "dmn"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.41"
common = { path = "../common" }
regex = "1.11.1"
uuid = { version = "1.16.0", features = ["serde", "v4"] }
